controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz
        use_sim_time: true  # If running in simulation

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/ImuSensorBroadcaster

        robot_joint_controller: # 控制器名称
            type: robot_joint_controller/RobotJointControllerGroup

robot_joint_controller:
    ros__parameters:
        joints:
            # isaacgym
            # - arm_l1_joint
            # - arm_l2_joint
            # - arm_l3_joint
            # - arm_l4_joint
            # - arm_l5_joint
            # - arm_l6_joint
            # - arm_l7_joint

            # - arm_r1_joint
            # - arm_r2_joint
            # - arm_r3_joint
            # - arm_r4_joint
            # - arm_r5_joint
            # - arm_r6_joint
            # - arm_r7_joint

            - leg_l1_joint
            - leg_l2_joint
            - leg_l3_joint            
            - leg_l4_joint
            - leg_l5_joint
            - leg_l6_joint

            - leg_r1_joint
            - leg_r2_joint
            - leg_r3_joint            
            - leg_r4_joint
            - leg_r5_joint
            - leg_r6_joint

imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: "imu_sensor"
        frame_id: imu_link